In [25]:
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0,
               31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0,
               35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8,
               10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0,
               500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0,
               700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7,
               7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

fish_data = [ [l, w] for l, w in zip(fish_length, fish_weight)]
fish_target = [1]*35 + [0]*14


In [26]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()


In [27]:
train_input = fish_data[:35]
train_target = fish_target[:35]
test_input = fish_data[35:]
test_target = fish_target[35:]


In [28]:
kn.fit(train_input, train_target)
kn.score(test_input, test_target)


0.0

In [29]:
import numpy as np

input_arr = np.array(fish_data)
target_arr = np.array(fish_target)


In [30]:
input_arr.shape


(49, 2)

In [31]:
np.random.seed(42)
index = np.arange(49)
np.random.shuffle(index)
index


array([13, 45, 47, 44, 17, 27, 26, 25, 31, 19, 12,  4, 34,  8,  3,  6, 40,
       41, 46, 15,  9, 16, 24, 33, 30,  0, 43, 32,  5, 29, 11, 36,  1, 21,
        2, 37, 35, 23, 39, 10, 22, 18, 48, 20,  7, 42, 14, 28, 38])

In [32]:
train_input = input_arr[index[:35]]
train_target = target_arr[index[:35]]

(input_arr[13], train_input[0])  # 0 --> 13 에 매핑되었으므로, 두개의 값이 동일해야 함


(array([ 32., 340.]), array([ 32., 340.]))

In [33]:
test_input = input_arr[index[35:]]
test_target = target_arr[index[35:]]


In [34]:
train_input[:, 0]

array([32. , 12.4, 14.3, 12.2, 33. , 36. , 35. , 35. , 38.5, 33.5, 31.5,
       29. , 41. , 30. , 29. , 29.7, 11.3, 11.8, 13. , 32. , 30.7, 33. ,
       35. , 41. , 38.5, 25.4, 12. , 39.5, 29.7, 37. , 31. , 10.5, 26.3,
       34. , 26.5])

In [41]:
# training set 과 test set 을 scatter plot 으로 그려보기

length = np.concatenate((train_input[:, 0], test_input[:, 0]), axis=0)
weight = np.concatenate([train_input[:, 1], test_input[:, 1]], axis=0)

classes = [ "train" if x < 35 else "test"  for x in range(0, 49)]

import pandas as pd
df = pd.DataFrame({"length": length, "weight": weight, "classes": classes})

import plotly.express as px
fig = px.scatter(df, x="length", y="weight", color="classes")
fig.show()

In [43]:
kn = kn.fit(train_input, train_target)


In [44]:
kn.score(test_input, test_target)


1.0

In [45]:
test_input


array([[ 10.6,   7. ],
       [  9.8,   6.7],
       [ 35. , 680. ],
       [ 11.2,   9.8],
       [ 31. , 475. ],
       [ 34.5, 620. ],
       [ 33.5, 610. ],
       [ 15. ,  19.9],
       [ 34. , 575. ],
       [ 30. , 390. ],
       [ 11.8,   9.9],
       [ 32. , 600. ],
       [ 36. , 850. ],
       [ 11. ,   9.7]])

In [46]:
kn.predict(test_input)


array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [47]:
test_target


array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])